### ISSUE TITLE
OpenFlow Controller using openflow protocol 1.5

### ISSUE THREAD

**Issue by arisetty** [lebauce/goloxi#1]
Hello,

Do you have any sample controller that uses openflow using this repo?
if so, could you please share.

Thanks
Chakri

**Comment by lebauce** [comment]
@arisetty I don't think there is any controller that uses this repo. The main user of this repository is Skydive (https://github.com/skydive-project/skydive) to parse Openvswitch Openflow rules :
* https://github.com/skydive-project/skydive/blob/master/topology/probes/ovsdb/ofnative.go
* https://github.com/skydive-project/skydive/blob/master/topology/probes/ovsdb/of15.go

That being said, it should be perfectly feasible to use to create an Openflow controller in Go as it's probably the most complete Golang library for OpenFlow

**Comment by arisetty** [comment]
@lebauce Thank you very much for your feedback. I'll attempt to write/modify a controller (https://github.com/Kmotiko/gofc.git) to support openflow 1.5. The current gofc controller uses only 1.3. I'll try to use this repo.
